---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.6

suites:
  - name: default
    run_list:
      - recipe[t3-pdns::default]
      - recipe[t3-pdns::test]
    attributes:
