---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-7.8

# This fails for at the `pdns_control reload` step with
# > Timeout error: Error from remote in receive(): Resource temporarily unavailable
#  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[t3-pdns::default]
      - recipe[t3-pdns::test]
    attributes:
