---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-7.11
    run_list:
      - recipe[apt]
  - name: debian-8.6
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[t3-pdns::default]
      - recipe[t3-pdns_test::default]
    attributes:
