---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-7.8
  - name: debian-8.5

suites:
  - name: default
    run_list:
      - recipe[t3-pdns::default]
      - recipe[t3-pdns::test]
    attributes:
