name             "t3-pdns"
maintainer       "Steffen Gebert"
maintainer_email "steffen.gebert@typo3.org"
license          "Apache2"
description      "Installs/Configures t3-pdns"
long_description "Installs/Configures t3-pdns"
version          "1.0.3"

depends          "pdns", "= 2.4.1"
depends          "zabbix-custom-checks", "~> 0.2.6"
